fix: pm2 not found case

diff --git a/.github/workflows/digitalocean.yml b/.github/workflows/digitalocean.yml
--- a/.github/workflows/digitalocean.yml
+++ b/.github/workflows/digitalocean.yml
@@ -28,7 +28,7 @@ jobs:
         cache: 'npm'
 
     - name: Stop previous notifier
-      run: pm2 stop 0
+      run: pm2 stop 0 || echo "PM2 process not found."
 
     - name: Dependencies install
       run: make init
